BEGIN TRAN 
if not exists(select 1 from cfg.vli_value_lists where vli_id = 'TodasJornadasSeleccione')
	INSERT cfg.vli_value_lists (vli_id, vli_description, vli_prompt, vli_value_source, vli_codfld, vli_enable_caching, vli_caching_expiration, vli_caching_expiration_mins, vli_definition, vli_fecha_grabacion, vli_usuario_grabacion, vli_fecha_modificacion, vli_usuario_modificacion) VALUES ('TodasJornadasSeleccione', 'Lista de todas las jornadas', 'Jornada', 'UseSqlExpressionInItemData', 'int', 0, 0, 0, '<List><Bound>select jor_codigo, jor_descripcion from (SELECT jor_codigo, jor_descripcion + '' - '' + jor_horario as jor_descripcion, 2 orden FROM sal.jor_jornadas UNION SELECT NULL, ''Seleccione'', 1) v order by orden, jor_descripcion</Bound></List>', '2016-07-12 11:55:50', 'admin', '2016-07-12 12:25:50', 'admin')
if not exists(select 1 from cfg.vli_value_lists where vli_id = 'TodasFrecuenciasPagoAcreedor')
	INSERT cfg.vli_value_lists (vli_id, vli_description, vli_prompt, vli_value_source, vli_codfld, vli_enable_caching, vli_caching_expiration, vli_caching_expiration_mins, vli_definition, vli_fecha_grabacion, vli_usuario_grabacion, vli_fecha_modificacion, vli_usuario_modificacion) VALUES ('TodasFrecuenciasPagoAcreedor', 'Todas las frecuencias de pago a acreedor que pueden ser configuradas al descuento ciclico', NULL, 'UseItemData', 'string', 0, 0, 0, '<List><Unbound><Item><ID>Quincenal</ID><Description>Quincenal</Description></Item><Item><ID>Mensual</ID><Description>Mensual</Description></Item></Unbound></List>', '2016-09-08 11:12:07', 'admin', NULL, NULL)

if not exists(select 1 from cfg.vli_value_lists where vli_id = 'TodosBancosYAcreedoresConRutaACH')
	INSERT cfg.vli_value_lists (vli_id, vli_description, vli_prompt, vli_value_source, vli_codfld, vli_enable_caching, vli_caching_expiration, vli_caching_expiration_mins, vli_definition, vli_fecha_grabacion, vli_usuario_grabacion, vli_fecha_modificacion, vli_usuario_modificacion) VALUES ('TodosBancosYAcreedoresConRutaACH', 'Lista todos los bancos y acreedores mostrando la ruta de ACH', NULL, 'UseSqlExpressionInItemData', 'int', 0, 0, 0, '<List><Bound>select bca_codigo, ruta_ach + '' - '' + banco from (select  bca_codigo, gen.lpad(gen.get_pb_field_data(bca_property_bag_data, ''bca_ruta''), 5, ''0'') ruta_ach, bca_nombre + '' ('' + pai_descripcion + '')'' banco from gen.bca_bancos_y_acreedores join gen.pai_paises on pai_codigo = bca_codpai) v order by convert(numeric, ruta_ach)</Bound></List>', '2016-03-30 10:23:31', 'admin', '2016-03-30 10:28:48', 'admin')

if not exists(select 1 from cfg.vli_value_lists where vli_id = 'TiposCuentaBancariaSeleccione')
	INSERT cfg.vli_value_lists (vli_id, vli_description, vli_prompt, vli_value_source, vli_codfld, vli_enable_caching, vli_caching_expiration, vli_caching_expiration_mins, vli_definition, vli_fecha_grabacion, vli_usuario_grabacion, vli_fecha_modificacion, vli_usuario_modificacion) VALUES ('TiposCuentaBancariaSeleccione', 'Tipos de cuenta bancaria para seleccionar', 'Seleccione', 'UseSqlExpressionInItemData', 'string', 0, 0, 1, '<List><Bound>select codigo, descripcion from (select ''P'' codigo, ''Préstamo'' descripcion, 2 orden union select ''C'', ''Corriente'', 2 orden union select ''A'', ''Ahorro'', 2 orden union select null, ''Seleccione'', 1 orden) v order by orden, descripcion</Bound></List>', '2016-10-05 15:42:32', 'admin', NULL, NULL)

if not exists(select 1 from cfg.vli_value_lists where vli_id = 'TodasFormasPagoSeleccione')
	INSERT cfg.vli_value_lists (vli_id, vli_description, vli_prompt, vli_value_source, vli_codfld, vli_enable_caching, vli_caching_expiration, vli_caching_expiration_mins, vli_definition, vli_fecha_grabacion, vli_usuario_grabacion, vli_fecha_modificacion, vli_usuario_modificacion) VALUES ('TodasFormasPagoSeleccione', 'Lista las formas de pago para seleccionar', 'seleccionar', 'UseItemData', 'int', 0, 0, 0, '<List><Bound>select fpa_codigo, fpa_descripcion from (select fpa_codigo, fpa_descripcion, 2 orden from exp.fpa_formas_pagos union select null, ''Seleccione'', 1 orden) v order by orden, fpa_descripcion</Bound></List>', '2016-10-05 14:48:31', 'admin', NULL, NULL)


PRINT 'Inserting values into pbf_property_bag_fields'
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'bca_forma_pago')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'BancosYAcreedores', 'bca_forma_pago', 'Forma de Pago', 'Forma de pago al acreedor', 'string', 'TodasFormasPago', 'DropDownList', NULL, NULL, 10, '2016-02-01 15:21:13', 'admin', NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'bca_ruta')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'BancosYAcreedores', 'bca_ruta', 'Ruta', 'Ruta de ACH para el pago', 'string', NULL, 'DropDownList', NULL, NULL, 20, '2016-02-01 15:21:13', 'admin', NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'exp_digito_verificador')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Expedientes', 'exp_digito_verificador', 'Dígito verificador', NULL, 'string', NULL, 'DropDownList', NULL, NULL, 10, NULL, NULL, NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'exp_clase_renta')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Expedientes', 'exp_clase_renta', 'Clase de renta', NULL, 'string', NULL, 'DropDownList', NULL, NULL, 20, NULL, NULL, NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'exp_numero_dependientes')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Expedientes', 'exp_numero_dependientes', 'Número de dependientes', NULL, 'int', NULL, 'DropDownList', NULL, NULL, 30, NULL, NULL, NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'exp_declara_ingresos')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Expedientes', 'exp_declara_ingresos', '¿Declara ingresos?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 40, NULL, NULL, NULL, NULL, 0)
if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_descuenta_seguro_social')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_descuenta_seguro_social', '¿Descuenta Seguro Social?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 10, NULL, NULL, NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_descuenta_seguro_educativo')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_descuenta_seguro_educativo', '¿Descuenta Seguro Educativo?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 20, NULL, NULL, NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_suspendido')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_suspendido', '¿Está suspendido?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 30, NULL, NULL, NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_renta')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_renta', '¿Descuenta Renta?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 40, NULL, NULL, NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_renta_gr')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_renta_gr', '¿Descuenta Renta Gasto Rep?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 50, NULL, NULL, NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_marca_tarjeta')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_marca_tarjeta', '¿Marca Reloj?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 60, NULL, NULL, '2016-06-13 15:31:38', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_horas_compensatorio')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_horas_compensatorio', 'Horas compensatorio', 'Indica el numero de horas que se pagan como compensatorio por el horario laborado', 'int', NULL, 'DropDownList', NULL, NULL, 0, '2016-03-04 15:28:02', 'liliana.mendez', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_codfpa')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_codfpa', 'Forma de pago', NULL, 'int', 'TodasFormasPagoSeleccione', 'DropDownList', NULL, NULL, 10, '2016-03-30 10:14:56', 'admin', '2016-10-05 14:48:44', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_tipo_cuenta_bancaria')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_tipo_cuenta_bancaria', 'Tipo cuenta bancaria', NULL, 'string', 'TiposCuentaBancariaSeleccione', 'DropDownList', NULL, NULL, 20, '2016-03-30 10:15:30', 'admin', '2016-10-05 15:43:07', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_codbca_ruta_ach')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_codbca_ruta_ach', 'Ruta ACH', NULL, 'int', 'TodosBancosYAcreedoresConRutaACH', 'DropDownList', NULL, NULL, 30, '2016-03-30 10:24:18', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_cuenta_bancaria')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_cuenta_bancaria', 'Cuenta bancaria', NULL, 'string', NULL, 'DropDownList', NULL, NULL, 25, '2016-03-30 10:25:13', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_frecuencia_pago')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_frecuencia_pago', 'Frecuencia de pago', NULL, 'string', 'TodasFrecuenciasPagoAcreedor', 'DropDownList', NULL, NULL, 0, '2016-03-30 10:33:30', 'admin', '2016-09-08 11:13:08', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_dia_libre')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_dia_libre', '¿Es día libre?', 'Indica si la jornada es utilizada para la programación de días libres', 'string', 'SiNo', 'DropDownList', NULL, NULL, 10, '2016-04-21 11:47:14', 'admin', '2016-04-21 14:49:37', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_rotativo')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_rotativo', '¿Es rotativo?', 'Indica si la jornada pertenece a los turnos rotativos', 'string', 'SiNo', 'DropDownList', NULL, NULL, 20, '2016-04-21 14:49:21', 'admin', '2016-04-21 15:08:37', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_nocturno')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_nocturno', '¿Es nocturno?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 30, '2016-04-27 12:31:18', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_dia_siguiente')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_dia_siguiente', '¿Toma Feriado/Libre del día siguiente?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 40, '2016-04-27 12:34:48', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_doble_turno')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_doble_turno', '¿Aplica doble turno?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 50, '2016-05-11 08:19:47', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'tpl_nombre_contable')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'TiposPlanillas', 'tpl_nombre_contable', 'Nombre contable', 'Nombre del tipo de planilla para ser mostrado en el asiento contable', 'string', NULL, 'DropDownList', NULL, NULL, 10, '2016-06-01 11:06:05', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'the_es_prestacion')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'TiposHoraExtra', 'the_es_prestacion', '¿Es prestación de la empresa?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 10, '2016-06-13 08:54:09', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cia_correlativo_css')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Companias', 'cia_correlativo_css', 'Correlativo', 'Correlativo asignado por la CSS', 'string', NULL, 'DropDownList', 'Preelaborada', NULL, 10, '2016-07-19 12:24:09', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cia_ruc')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Companias', 'cia_ruc', 'RUC', NULL, 'string', NULL, 'DropDownList', 'Preelaborada', NULL, 20, '2016-07-19 12:24:32', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cia_digito_verificador')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Companias', 'cia_digito_verificador', 'Dígito Verificador', NULL, 'string', NULL, 'DropDownList', 'Preelaborada', NULL, 30, '2016-07-19 12:26:06', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cia_licencia')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Companias', 'cia_licencia', 'Licencia', NULL, 'string', NULL, 'DropDownList', 'Preelaborada', NULL, 40, '2016-07-19 12:29:55', 'admin', '2016-07-19 12:31:02', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'tcc_orden_aplicacion')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'TiposDescuentoCiclico', 'tcc_orden_aplicacion', 'Orden de Aplicación', NULL, 'int', NULL, 'DropDownList', NULL, NULL, 10, '2016-07-25 09:02:40', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'emp_firmante')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Empleos', 'emp_firmante', '¿Firma Contrato de Trabajo?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 70, '2016-08-16 09:25:42', 'admin', '2016-08-16 09:25:42', 'admin', 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_numero_prestamo')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_numero_prestamo', 'Número de Préstamo', NULL, 'string', NULL, 'DropDownList', NULL, NULL, 23, '2016-09-01 17:12:59', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_valor_cuota_primera_quincena')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_valor_cuota_primera_quincena', 'Valor Cuota Primera Quincena', NULL, 'double', NULL, 'DropDownList', 'Cuota Mensual Impar', NULL, 30, '2016-09-08 10:22:27', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_valor_cuota_segunda_quincena')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_valor_cuota_segunda_quincena', 'Valor Cuota Segunda Quincena', NULL, 'double', NULL, 'DropDownList', 'Cuota Mensual Impar', NULL, 40, '2016-09-08 10:23:55', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_monto_impar')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_monto_impar', 'Monto', NULL, 'double', NULL, 'DropDownList', 'Cuota Mensual Impar', NULL, 10, '2016-09-08 10:24:53', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'dcc_saldo_impar')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'DescuentosCiclicos', 'dcc_saldo_impar', 'Saldo', NULL, 'double', NULL, 'DropDownList', 'Cuota Mensual Impar', NULL, 20, '2016-09-08 10:25:58', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cdc_saldo_anterior')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'CuotasDescuentoCiclico', 'cdc_saldo_anterior', 'Saldo Anterior', 'Almacena el saldo que tenía el descuento cíclico antes de aplicar la cuota en planila', 'double', NULL, 'DropDownList', NULL, NULL, 10, '2016-09-10 16:16:42', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'cdc_saldo_nuevo')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'CuotasDescuentoCiclico', 'cdc_saldo_nuevo', 'Saldo Nuevo', 'Almacena el saldo luego de aplicar en planilla la cuota al saldo anterior', 'double', NULL, 'DropDownList', NULL, NULL, 20, '2016-09-10 16:17:16', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_codjor_entrada')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_codjor_entrada', 'Jornada al Iniciar Turno', NULL, 'int', 'TodasJornadasSeleccione', 'DropDownList', 'Doble Turno', NULL, 10, '2016-09-23 14:23:36', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'jor_codjor_salida')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'Jornadas', 'jor_codjor_salida', 'Jornada al Terminar Turno', NULL, 'int', 'TodasJornadasSeleccione', 'DropDownList', 'Doble Turno', NULL, 20, '2016-09-23 14:23:59', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'sdv_codigo_planilla')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'SolicitudesVacaciones', 'sdv_codigo_planilla', 'Período de Planilla', NULL, 'string', NULL, 'DropDownList', NULL, NULL, 10, '2016-10-11 14:29:06', 'admin', NULL, NULL, 0)

if not exists(select 1 from cfg.pbf_property_bag_fields where pbf_field_name =  'gra_aplica_prestacion_nacional')
	INSERT cfg.pbf_property_bag_fields (pbf_entidad, pbf_field_name, pbf_prompt_loc_key, pbf_descripcion_loc_key, pbf_codfld, pbf_codvli, pbf_list_mode, pbf_group_loc_key, pbf_controller_action_name, pbf_orden, pbf_fecha_grabacion, pbf_usuario_grabacion, pbf_fecha_modificacion, pbf_usuario_modificacion, pbf_requerido) VALUES ( 'GruposAsistencias', 'gra_aplica_prestacion_nacional', '¿Aplica prestación de día nacional?', NULL, 'string', 'SiNo', 'DropDownList', NULL, NULL, 0, '2016-11-11 18:14:34', 'admin', '2016-11-11 18:14:56', 'admin', 0)

PRINT 'Done'

commit tran
