DELETE FROM sal.tpl_tipo_planilla 
SET NOCOUNT ON 
SET IDENTITY_INSERT [sal].[tpl_tipo_planilla] ON
GO

PRINT 'Inserting values into tpl_tipo_planilla'

INSERT sal.tpl_tipo_planilla (tpl_codigo, tpl_codigo_visual, tpl_codcia, tpl_codmon, tpl_descripcion, tpl_frecuencia, tpl_aplicacion, tpl_num_periodo, tpl_total_periodos, tpl_codtpl_normal, tpl_hex_rango_fechas_ingreso, tpl_hex_offset_rango_fechas, tpl_hex_override_fecha_fin, tpl_hex_rango_fecha_fin, tpl_hex_offset_fecha_fin, tpl_asi_rango_fechas_ingreso, tpl_asi_offset_rango_fechas, tpl_asi_override_fecha_fin, tpl_asi_rango_fecha_fin, tpl_asi_offset_fecha_fin, tpl_permite_trans_luego_corte, tpl_ignora_aut_luego_corte, tpl_traslada_trans_ignoradas, tpl_genera_proximo_periodo, tpl_property_bag_data, tpl_usuario_grabacion, tpl_fecha_grabacion, tpl_usuario_modificacion, tpl_fecha_modificacion) VALUES (1, '1', 1, 'PAB', 'Planilla Quincenal', 'Quincenal', 'Normal', 20, 24, NULL, 'UsarFechasCorte', 2, 0, 'PeriodoActual', NULL, 'UsarFechasCorte', 2, 0, 'PeriodoActual', NULL, 1, 0, 0, 1, '<DocumentElement><TiposPlanillas><tpl_nombre_contable>REGULAR</tpl_nombre_contable></TiposPlanillas></DocumentElement>', NULL, NULL, 'admin', '2016-06-01 11:25:41')
INSERT sal.tpl_tipo_planilla (tpl_codigo, tpl_codigo_visual, tpl_codcia, tpl_codmon, tpl_descripcion, tpl_frecuencia, tpl_aplicacion, tpl_num_periodo, tpl_total_periodos, tpl_codtpl_normal, tpl_hex_rango_fechas_ingreso, tpl_hex_offset_rango_fechas, tpl_hex_override_fecha_fin, tpl_hex_rango_fecha_fin, tpl_hex_offset_fecha_fin, tpl_asi_rango_fechas_ingreso, tpl_asi_offset_rango_fechas, tpl_asi_override_fecha_fin, tpl_asi_rango_fecha_fin, tpl_asi_offset_fecha_fin, tpl_permite_trans_luego_corte, tpl_ignora_aut_luego_corte, tpl_traslada_trans_ignoradas, tpl_genera_proximo_periodo, tpl_property_bag_data, tpl_usuario_grabacion, tpl_fecha_grabacion, tpl_usuario_modificacion, tpl_fecha_modificacion) VALUES (2, '2', 1, 'PAB', 'Planilla Décimo III mes', 'Mensual', 'Especial', 5, 12, NULL, 'UsarFechasCorte', 0, 0, 'PeriodoActual', NULL, 'UsarFechasCorte', 0, 0, 'PeriodoActual', NULL, 1, 0, 0, 1, '<DocumentElement><TiposPlanillas><tpl_nombre_contable>DECIMO TERCERO</tpl_nombre_contable></TiposPlanillas></DocumentElement>', NULL, NULL, 'lmendez', '2016-08-12 16:59:07')
INSERT sal.tpl_tipo_planilla (tpl_codigo, tpl_codigo_visual, tpl_codcia, tpl_codmon, tpl_descripcion, tpl_frecuencia, tpl_aplicacion, tpl_num_periodo, tpl_total_periodos, tpl_codtpl_normal, tpl_hex_rango_fechas_ingreso, tpl_hex_offset_rango_fechas, tpl_hex_override_fecha_fin, tpl_hex_rango_fecha_fin, tpl_hex_offset_fecha_fin, tpl_asi_rango_fechas_ingreso, tpl_asi_offset_rango_fechas, tpl_asi_override_fecha_fin, tpl_asi_rango_fecha_fin, tpl_asi_offset_fecha_fin, tpl_permite_trans_luego_corte, tpl_ignora_aut_luego_corte, tpl_traslada_trans_ignoradas, tpl_genera_proximo_periodo, tpl_property_bag_data, tpl_usuario_grabacion, tpl_fecha_grabacion, tpl_usuario_modificacion, tpl_fecha_modificacion) VALUES (3, '3', 1, 'PAB', 'Planilla Vacaciones', 'Anual', 'Especial', 1, 1, 1, 'UsarFechasCorte', 0, 0, 'PeriodoActual', NULL, 'PeriodoActual', 0, 0, 'PeriodoActual', NULL, 1, 0, 0, 1, '<DocumentElement><TiposPlanillas><tpl_nombre_contable>VACACIONES</tpl_nombre_contable></TiposPlanillas></DocumentElement>', NULL, NULL, 'admin', '2016-06-01 11:26:33')
INSERT sal.tpl_tipo_planilla (tpl_codigo, tpl_codigo_visual, tpl_codcia, tpl_codmon, tpl_descripcion, tpl_frecuencia, tpl_aplicacion, tpl_num_periodo, tpl_total_periodos, tpl_codtpl_normal, tpl_hex_rango_fechas_ingreso, tpl_hex_offset_rango_fechas, tpl_hex_override_fecha_fin, tpl_hex_rango_fecha_fin, tpl_hex_offset_fecha_fin, tpl_asi_rango_fechas_ingreso, tpl_asi_offset_rango_fechas, tpl_asi_override_fecha_fin, tpl_asi_rango_fecha_fin, tpl_asi_offset_fecha_fin, tpl_permite_trans_luego_corte, tpl_ignora_aut_luego_corte, tpl_traslada_trans_ignoradas, tpl_genera_proximo_periodo, tpl_property_bag_data, tpl_usuario_grabacion, tpl_fecha_grabacion, tpl_usuario_modificacion, tpl_fecha_modificacion) VALUES (4, '4', 1, 'PAB', 'Planilla Intermedia', 'Quincenal', 'Especial', 0, 0, NULL, 'UsarFechasCorte', NULL, 0, 'PeriodoActual', NULL, 'PeriodoActual', NULL, 0, 'PeriodoActual', NULL, 1, 0, 0, 0, '<DocumentElement><TiposPlanillas><tpl_nombre_contable>INTERMEDIA</tpl_nombre_contable></TiposPlanillas></DocumentElement>', 'admin', '2016-01-28 09:04:38', 'admin', '2016-06-01 11:27:02')
INSERT sal.tpl_tipo_planilla (tpl_codigo, tpl_codigo_visual, tpl_codcia, tpl_codmon, tpl_descripcion, tpl_frecuencia, tpl_aplicacion, tpl_num_periodo, tpl_total_periodos, tpl_codtpl_normal, tpl_hex_rango_fechas_ingreso, tpl_hex_offset_rango_fechas, tpl_hex_override_fecha_fin, tpl_hex_rango_fecha_fin, tpl_hex_offset_fecha_fin, tpl_asi_rango_fechas_ingreso, tpl_asi_offset_rango_fechas, tpl_asi_override_fecha_fin, tpl_asi_rango_fecha_fin, tpl_asi_offset_fecha_fin, tpl_permite_trans_luego_corte, tpl_ignora_aut_luego_corte, tpl_traslada_trans_ignoradas, tpl_genera_proximo_periodo, tpl_property_bag_data, tpl_usuario_grabacion, tpl_fecha_grabacion, tpl_usuario_modificacion, tpl_fecha_modificacion) VALUES (5, '5', 1, 'PAB', 'Planilla de Liquidaciones', 'Quincenal', 'Especial', 0, 0, NULL, 'UsarFechasCorte', NULL, 0, 'PeriodoActual', NULL, 'PeriodoActual', NULL, 0, 'PeriodoActual', NULL, 1, 0, 0, 0, '<DocumentElement><TiposPlanillas><tpl_nombre_contable>LIQUIDACIONES</tpl_nombre_contable></TiposPlanillas></DocumentElement>', 'admin', '2016-01-28 09:04:38', 'admin', '2016-06-01 11:26:51')

PRINT 'Done'
 
 
SET IDENTITY_INSERT [sal].[tpl_tipo_planilla] OFF
GO
SET NOCOUNT OFF
