 
SET NOCOUNT ON

--Se eliminan asociaciones y agrupadores de Panamá
 DELETE FROM sal.iag_ingresos_agrupador WHERE iag_codagr IN (SELECT agr_codigo FROM sal.agr_agrupadores WHERE agr_codpai='pa')
 DELETE FROM sal.dag_descuentos_agrupador WHERE dag_codagr IN (SELECT agr_codigo FROM sal.agr_agrupadores WHERE agr_codpai='pa')
 DELETE FROM sal.agr_agrupadores WHERE agr_codpai='pa'



SET IDENTITY_INSERT [sal].[agr_agrupadores] ON
GO
 
 
PRINT 'Inserting values into agr_agrupadores'

INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (28, 'pa', 'Base Cálculo Seguro Social', 'BaseCalculoSeguroSocial', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (29, 'pa', 'Base Cálculo Seguro Educativo', 'BaseCalculoSeguroEducativo', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (30, 'pa', 'Agrupador Para Ingresos Renta PTY', 'IngresosRentaPTY', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (31, 'pa', 'Agrupador Ingresos Renta GRep PTY', 'IngresosRentaGRepPTY', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (32, 'pa', 'Agrupador Descuentos de Renta PTY', 'DescuentosRentaPTY', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (33, 'pa', 'Ingresos Salario para Cálculo de Decimo Tercero', 'IngresosSalarioXIII', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (34, 'pa', 'Base Cálculo Reserva Seguro Social', 'BaseCalculoReservaSS', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (35, 'pa', 'Base Cálculo Reserva Seguro Social XIII', 'BaseCalculoReservaSSXIII', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (36, 'pa', 'Base Cálculo Reserva Seguro Educativo', 'BaseCalculoReservaSE', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (37, 'pa', 'Base Cálculo Reserva Indemnización', 'BaseCalculoReservaIndem', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (38, 'pa', 'Base Cálculo Reserva Prima de Antigüedad', 'BaseCalculoReservaPrima', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (39, 'pa', 'Base Cálculo Provisión Vacación', 'BaseCalculoReservaVac', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (40, 'pa', 'Base Cálculo Provisión XIII Mes', 'BaseCalculoReservaXIII', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (41, 'pa', 'Base Cálculo Provisión Riesgo Profesional', 'BaseCalculoReservaRiesgo', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (42, 'pa', 'Agrupador para Descuentos GRep PTY', 'DescuentosRentaGRepPTY', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (43, 'pa', 'XIII Mes', 'XIIIMes', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (44, 'pa', 'XIII Mes GR', 'XIIIMesGR', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (45, 'pa', 'Ingresos Para Cálculo de Vacación (Salarios)', 'IngresosVacacion', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (46, 'pa', 'Ingresos Gasto de Representación para Cálculo de Décimo Tercero', 'IngresosGRepXIII', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (47, 'pa', 'PA - Planilla - SALARIO', 'ING - SALARIO', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (48, 'pa', 'PA - Planilla - GTOREP', 'ING - GTOREP', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (49, 'pa', 'PA - Planilla - INCAP', 'ING - INCAP', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (50, 'pa', 'PA - Planilla - COMPENSATORIO', 'ING - COMPENSATORIO', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (51, 'pa', 'PA - Planilla - EXTRA', 'ING - EXTRA', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (52, 'pa', 'PA - Planilla - ISR', 'DED - ISR', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (53, 'pa', 'DED - ISRGTO', 'DED - ISRGTO', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (54, 'pa', 'DED - SEGUROSOCIAL', 'DED - SEGUROSOCIAL', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (55, 'pa', 'DED - SEGUROEDUCATIVO', 'DED - SEGUROEDUCATIVO', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (56, 'pa', 'Preelaborada SIPE - Salario', 'PA_Pree_Sipe_Salario', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (57, 'pa', 'Preelaborada SIPE - Horas Extras', 'PA_Pree_Sipe_Extras', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (58, 'pa', 'Preelaborada SIPE - Vacación', 'PA_Pree_Sipe_Vacacion', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (59, 'pa', 'Preelaborada SIPE - Gasto de Representación', 'PA_Pree_Sipe_GR', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (60, 'pa', 'Preelaborada SIPE - Bonificación', 'PA_Pree_Sipe_Bono', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (61, 'pa', 'Preelaborada SIPE - Décimo Tercer Mes', 'PA_Pree_Sipe_XIII', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (62, 'pa', 'Preelaborada SIPE - ISR', 'PA_Pree_Sipe_ISR', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (63, 'pa', 'Preelaborada SIPE - Participación', 'PA_Pree_Sipe_Participacion', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (64, 'pa', 'Preelaborada SIPE - Viáticos de Transporte', 'PA_Pree_Sipe_Viatico', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (65, 'pa', 'Preelaborada SIPE - Prestaciones Liquidación', 'PA_Pree_Sipe_Liq', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (66, 'pa', 'Preelaborada SIPE - Preaviso', 'PA_Pree_Sipe_Preaviso', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (67, 'pa', 'Preelaborada SIPE - Otros Ingresos', 'PA_Pree_Sipe_OtrosIng', 0, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (68, 'pa', 'Fondo de Cesantía: Salario', 'PA_Fondo_Cesantia_Salario', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (69, 'pa', 'Fondo de Cesantía: Gasto de Representación', 'PA_Fondo_Cesantia_GR', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (70, 'pa', 'Preelaborada: Salario (03)', 'PA_Pree_Salario', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (71, 'pa', 'Preelaborada: Gastos de Representacion (73)', 'PA_Pree_GR', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (72, 'pa', 'Preelaborada: Otros Salarios', 'PA_Pree_OtrosSal', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (73, 'pa', 'Preelaborada: Bono (75)', 'PA_Pree_Bono', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (74, 'pa', 'Preelaborada: Gratificaciones (74)', 'PA_Pree_Gratificacion', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (75, 'pa', 'Ingresos Gastos Representación (Anexo 03)', 'IngresosGR_Anexo03', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (76, 'pa', 'Ingresos Bonificación (Anexo 03)', 'IngresosBono_Anexo03', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (77, 'pa', 'Ingreso Salarios (Anexo 03)', 'IngresosSalario_Anexo03', 1, 'TodosExcluyendo', NULL, 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (78, 'pa', 'Preelaborada: Prima de Producción (81)', 'PA_Pree_PrimaProd', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (79, 'pa', 'Preelaborada: XIII Salario (03)', 'PA_Pree_Salario_XIII', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (80, 'pa', 'Preelaborada: XIII Gastos de Representacion (73)', 'PA_Pree_GR_XIII', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (81, 'pa', 'Preelaborada SIPE - ISR Gasto de Representación', 'PA_Pree_Sipe_ISR_GR', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (83, 'pa', 'Preelaborada SIPE - Gratificación', 'PA_Pree_Sipe_Gratificacion', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (84, 'pa', 'Preelaborada SIPE - Prima de Producción', 'PA_Pree_Sipe_Prima_Prod', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (85, 'pa', 'Descuentos por TNT para planilla columnar', 'DED - TNT', 0, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (87, 'pa', 'Base Cálculo Provisión Vacación Gasto Representación', 'BaseCalculoReservaVacGRep', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)
INSERT sal.agr_agrupadores (agr_codigo, agr_codpai, agr_descripcion, agr_abreviatura, agr_para_calculo, agr_modo_asociacion_tpl, agr_property_bag_data, agr_usuario_grabacion, agr_fecha_grabacion, agr_usuario_modificacion, agr_fecha_modificacion) VALUES (88, 'pa', 'Ingresos Para Cálculo de Vacación (Gasto Rep)', 'IngresosVacacionGRep', 1, 'TodosExcluyendo', '', 'Administrador', '2017-01-16 10:29:31', NULL, NULL)

PRINT 'Done'
 
 
SET IDENTITY_INSERT [sal].[agr_agrupadores] OFF
GO
SET NOCOUNT OFF
