 DELETE FROM gen.par_parametros WHERE par_codigo LIKE '%agrupa%'

SET NOCOUNT ON
 
 
PRINT 'Inserting values into par_parametros'
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Anexo03_CodigoAgrupador_Bono', 'Código del agrupador para el Bono del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Anexo03_CodigoAgrupador_GastoRep', 'Código del agrupador para el Gasto de Representación del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Anexo03_CodigoAgrupador_Salario', 'Código del agrupador para el Salario del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('BaseXIII_GastoRep_CodigoAgrupador', 'Código del agrupador para el base cálculo del décimo tercero del gasto de representación', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-08-04 08:28:44', NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('BaseXIII_Salario_CodigoAgrupador', 'Código del agrupador para el base cálculo del décimo tercero del salario', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-08-04 08:26:49', NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('EndeudamientoCodAgrupador', 'Abreviatura de Agrupador para validar el endeudamiento de un empleado (determina el listado de ingresos / descuentos a sumar para verificar el porcentaje de endeudamiento)', 'String', 'Identificador', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('EndeudamientoCodAgrupadorVar', 'Abreviatura de Agrupador de Ingresos Variables para validar el endeudamiento de un empleado (determina el listado de ingresos / descuentos para obtener el promedio de salarios variables que suman a los ingresos fijos)', 'String', 'Identificador', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('FondoCesantia_CodAgrupador_GastoRep', NULL, 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-06-28 08:40:54')
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('FondoCesantia_CodAgrupador_Salario', NULL, 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-06-28 08:41:17')
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Preelaborada_CodigoAgrupador_Bono', 'Código del agrupador para el Bono del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Preelaborada_CodigoAgrupador_GastoRep', 'Código del agrupador para el Gasto de Representación del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Preelaborada_CodigoAgrupador_Gratificacion', 'Código del agrupador para Gratificaciones del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Preelaborada_CodigoAgrupador_Otros', 'Código del agrupador para Otros Salarios del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('Preelaborada_CodigoAgrupador_Salario', 'Código del agrupador para el Salario del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Bono', 'Código de agrupador para el Informe Preelaborada SIPE columna Bonificación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Extras', 'Código de agrupador para el Informe Preelaborada SIPE columna Horas Extras', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_GastoRep', 'Código de agrupador para el Informe Preelaborada SIPE columna Gasto de Representación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Gratificacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Gratificación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-07-21 12:58:55')
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_ISR', 'Código de agrupador para el Informe Preelaborada SIPE columna ISR', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_ISR_GR', 'Código de agrupador para el Informe Preelaborada SIPE columna ISR Gasto Representación', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-07-21 08:30:35', NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Liquidacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Prestaciones Liquidación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_OtrosIngresos', 'Código de agrupador para el Informe Preelaborada SIPE columna Otros Ingresos', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Participacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Participación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Preaviso', 'Código de agrupador para el Informe Preelaborada SIPE columna Preaviso', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Prima_Prod', 'Código de agrupador para el Informe Preelaborada SIPE columna Prima de Producción', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-07-21 13:24:53', NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Salario', 'Código de agrupador para el Informe Preelaborada SIPE columna Salario', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Vacacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Vacación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_Viaticos', 'Código de agrupador para el Informe Preelaborada SIPE columna Viáticos', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
INSERT gen.par_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES ('PreelaboradaSIPE_CodigoAgrupador_XIII', 'Código de agrupador para el Informe Preelaborada SIPE columna XIII mes', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL)
PRINT 'Done'
 
 
SET NOCOUNT OFF
