 
SET NOCOUNT ON
 
SET IDENTITY_INSERT [gen].[apa_alcances_parametros] ON
GO
 
 
PRINT 'Inserting values into apa_alcances_parametros'

INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2315, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '60', NULL, NULL, 'admin', '2016-07-21 08:25:26')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2316, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Extras', 'pa', NULL, NULL, NULL, '57', NULL, NULL, 'admin', '2016-07-21 08:25:53')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2317, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '59', NULL, NULL, 'admin', '2016-07-21 08:26:15')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2318, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_ISR', 'pa', NULL, NULL, NULL, '62', NULL, NULL, 'admin', '2016-07-21 08:26:33')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2319, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Liquidacion', 'pa', NULL, NULL, NULL, '65', NULL, NULL, 'admin', '2016-07-21 08:26:58')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2320, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_OtrosIngresos', 'pa', NULL, NULL, NULL, '67', NULL, NULL, 'admin', '2016-07-21 08:27:20')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2321, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Participacion', 'pa', NULL, NULL, NULL, '63', NULL, NULL, 'admin', '2016-07-21 08:27:36')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2322, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Preaviso', 'pa', NULL, NULL, NULL, '66', NULL, NULL, 'admin', '2016-07-21 08:27:56')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2323, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '56', NULL, NULL, 'admin', '2016-07-21 08:28:11')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2324, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Vacacion', 'pa', NULL, NULL, NULL, '58', NULL, NULL, 'admin', '2016-07-21 08:28:26')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2325, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Viaticos', 'pa', NULL, NULL, NULL, '64', NULL, NULL, 'admin', '2016-07-21 08:28:48')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2326, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_XIII', 'pa', NULL, NULL, NULL, '61', NULL, NULL, 'admin', '2016-07-21 08:29:05')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2327, NULL, NULL, 'Anexo03_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '1055', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2328, NULL, NULL, 'Anexo03_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '75', NULL, NULL, 'admin', '2016-09-13 08:13:10')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2329, NULL, NULL, 'Anexo03_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '77', NULL, NULL, 'admin', '2016-09-13 08:11:14')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2333, NULL, NULL, 'Preelaborada_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '1052', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2334, NULL, NULL, 'Preelaborada_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '1050', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2335, NULL, NULL, 'Preelaborada_CodigoAgrupador_Gratificacion', 'pa', NULL, NULL, NULL, '1053', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2336, NULL, NULL, 'Preelaborada_CodigoAgrupador_Otros', 'pa', NULL, NULL, NULL, '1051', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2337, NULL, NULL, 'Preelaborada_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '1049', NULL, NULL, NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2338, NULL, NULL, 'FondoCesantia_CodAgrupador_Salario', 'pa', NULL, NULL, NULL, '68', NULL, NULL, 'admin', '2016-06-28 08:40:38')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (2339, NULL, NULL, 'FondoCesantia_CodAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '69', NULL, NULL, 'admin', '2016-06-28 08:41:04')
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (3341, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_ISR_GR', 'pa', NULL, NULL, NULL, '81', 'admin', '2016-07-21 08:30:51', NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (3342, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Gratificacion', 'pa', NULL, NULL, NULL, '83', 'admin', '2016-07-21 12:58:52', NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (3343, NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Prima_Prod', 'pa', NULL, NULL, NULL, '84', 'admin', '2016-07-21 13:25:13', NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (3344, NULL, NULL, 'BaseXIII_Salario_CodigoAgrupador', 'pa', NULL, NULL, NULL, '33', 'admin', '2016-08-04 08:27:52', NULL, NULL)
INSERT gen.apa_alcances_parametros (apa_codigo, apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (3345, NULL, NULL, 'BaseXIII_GastoRep_CodigoAgrupador', 'pa', NULL, NULL, NULL, '46', 'admin', '2016-08-04 08:28:59', NULL, NULL)


PRINT 'Done'
 
 
SET IDENTITY_INSERT [gen].[apa_alcances_parametros] OFF
GO
SET NOCOUNT OFF
