/****** Object:  UserDefinedFunction [sal].[fn_dias_domingo]    Script Date: 12/7/2016 11:56:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [sal].[fn_dias_domingo](@FECHA_INICIO DATETIME, @FECHA_FIN DATETIME) 
RETURNS INT AS
BEGIN
DECLARE @DIA_DOMINGO INT

SET @DIA_DOMINGO = 0

WHILE @FECHA_FIN >= @FECHA_INICIO
BEGIN
	IF DATEPART(dw, @FECHA_INICIO) = 1
	BEGIN
		SET @DIA_DOMINGO = @DIA_DOMINGO + 1
	END
	SET @FECHA_INICIO = @FECHA_INICIO + 1 
END
			
RETURN @DIA_DOMINGO		

END

GO


