BEGIN TRY
BEGIN TRANSACTION
DECLARE @codcia INT = 6;

INSERT into [sal].[ftp_formulacion_tipos_planilla] ([ftp_codtpl],[ftp_prefijo],[ftp_table_name],[ftp_codfac_filtro],[ftp_codfcu_loop],[ftp_sp_inicializacion],[ftp_sp_finalizacion],[ftp_sp_autorizacion]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'aju','pa.aju_ajustes','7217DB5E-140E-436F-BC30-A21EEB5098B8',(select fcu_codigo from (select RowNum = row_number() OVER ( order by fcu_codigo ), fcu_codigo from sal.fcu_formulacion_cursores where fcu_codpai = 'pa' and fcu_proceso = 'Planilla') tcr where tcr.RowNum = 42),'pa.GenPla_Inicializacion','pa.GenPla_Finalizacion','pa.aupla_Autoriza_planilla');
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'7217DB5E-140E-436F-BC30-A21EEB5098B8',1,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'D08AF6E4-0DA0-48A5-A46A-7917F2C90C5D',10,NULL,(select top 1 tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'ISR' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'5CBE3135-6C4A-46AC-8927-FCACE58FAD04',12,NULL,(select top 1 tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'ISRGR' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'213D36BC-452A-444D-9814-F826136D52B4',13,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'74A11C69-2905-4645-9CA6-225EF691E0D3',14,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'7D1AF3D1-70A8-4168-8C97-E62AEFBA44B2',2,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'1168CFE1-DEB7-4635-AC83-98B929C65E25',5,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'52B98440-8B49-4F68-82D8-5A759D306FFD',11,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'C2EB06BF-4002-4628-8E86-5B1C88CC0F6D',9,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'0C62DA23-33DF-457D-A7E2-49C0DE23F86F',6,NULL,(select top 1 tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'Seg Soc' AND tdc_codcia = @codcia),(select top 1 trs_codigo from sal.trs_tipos_reserva where trs_abreviatura = 'PROV_INDEM' AND trs_codcia = @codcia),1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'D0EE2447-A9ED-40B9-AD16-B2FA76F70C5D',7,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'8715BE23-2AD6-41AA-836C-E015C4BF9F71',8,NULL,(select top 1 tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'Seg Educ' AND tdc_codcia = @codcia),(select top 1 trs_codigo from sal.trs_tipos_reserva where trs_abreviatura = 'PROV_Prima_Anti' AND trs_codcia = @codcia),1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'B023400F-182F-4905-848E-1529A8266869',3,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Intermedia' and tpl_codmon='PAB'),'d01c3419-19d4-4852-ae64-ffd7371186cf',4,NULL,NULL,NULL,1);
COMMIT TRANSACTION
END TRY
BEGIN CATCH
	THROW;
END CATCH
