BEGIN TRY
	BEGIN TRANSACTION
	DECLARE @codcia INT = 6;

INSERT into [sal].[ftp_formulacion_tipos_planilla] 
([ftp_codtpl],[ftp_prefijo],[ftp_table_name],[ftp_codfac_filtro],[ftp_codfcu_loop],[ftp_sp_inicializacion],[ftp_sp_finalizacion],[ftp_sp_autorizacion]) values 
((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'qui','pa.qui_quincenal','1c322de6-4789-4232-bc28-a148e5e45a8e',(select fcu_codigo from (select RowNum = row_number() OVER ( order by fcu_codigo ), fcu_codigo from sal.fcu_formulacion_cursores where fcu_codpai = 'pa' and fcu_proceso = 'Planilla') tcr where tcr.RowNum = 12),'pa.GenPla_Inicializacion','pa.GenPla_Finalizacion','pa.aupla_autoriza_planilla');

insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'1c322de6-4789-4232-bc28-a148e5e45a8e',1,NULL,NULL,NULL,0);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'dd8c90cd-3e65-431a-b301-65b19c4c1f35',2,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'86d5188e-2120-49b9-8b98-a57a2d7772bd',4,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'c1e6999c-9b4d-4a8d-825b-ef938d1891d1',5,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'6bbc67e0-c6cd-490c-9257-2d496a48735d',6,(select tig_codigo from sal.tig_tipos_ingreso where tig_abreviatura = 'Salario' AND tig_codcia = @codcia),NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'5170a1c5-de74-4d09-b6dd-e324c59613ac',7,(select tig_codigo from sal.tig_tipos_ingreso where tig_abreviatura = 'Gasto Rep' AND tig_codcia = @codcia),NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'fe0ffacf-fa45-4ecc-8748-5e70b6b21467',8,(select tig_codigo from sal.tig_tipos_ingreso where tig_abreviatura = 'Retroactivo' AND tig_codcia = @codcia),NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'0894c89e-3154-40a8-adef-5fac024b0201',9,(select tig_codigo from sal.tig_tipos_ingreso where tig_abreviatura = 'Retroactivo GR' AND tig_codcia = @codcia),NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'eefe89cd-86f4-4847-8c8c-f84a3dcd5ed4',10,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'8d60069a-0beb-41ea-977f-600fc6e41574',11,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'42d8a080-a9a5-47f1-8229-99bb6ed71efc',12,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'Fondo Incap Agotado' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'72d579d4-c281-4569-b4e9-f61ed36bdae3',13,(select tig_codigo from sal.tig_tipos_ingreso where tig_abreviatura = 'Certificado Medico' AND tig_codcia = @codcia),NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'1050797b-a815-4051-a694-2221f8690858',14,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'ff7a9453-e976-4dd6-a080-4d8c06ac814d',15,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'TNT' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'414ac74e-04fb-4441-b8ca-f50162b95dbb',16,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'77ebc94e-3505-46e0-9f32-b6c4475d1e6b',17,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'8e473186-3b82-4b7f-9f25-b5ee874e5124',18,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'723cfb33-aea2-434d-a573-56e93fb236b6',19,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'0d214ad6-e1ef-4500-aa69-51fbe539c264',20,NULL,NULL,NULL,0);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'f0017293-0f88-4516-b35c-4964d32e292b',21,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'85ae6a9f-ceff-45dd-9cff-af297e52b69f',22,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'f9dc52a5-30ea-4957-9f17-54954d0a4a7e',23,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'9c60e57a-b6c2-43cf-89b6-61cb8b122bf9',24,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'f62949ca-2c72-48d0-a55e-b055b0901064',25,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'Seg Soc' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'48ea6d65-29b5-4da8-9dab-4f0e5592bf0d',26,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'59c6d4c3-e1d5-46d0-9641-ea7994f7e124',27,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'3a659999-3b6a-4906-845c-8ac750e90c8a',28,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'Seg Educ' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'0b6f201f-7443-4aa8-a466-e670027ad6b4',29,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'fd68b0c7-2e7c-4ad5-89e4-fab4f61c8f0b',30,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'c5dc36f7-0685-4a27-a9a5-824f8aeaa292',31,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'a22c44d2-0eba-4a41-9784-90484819f221',32,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'d1465930-c563-44d2-98a7-b27f9461b79e',33,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'ISR' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'82e83429-b3d4-4dd6-ac0c-c0749d423e48',34,NULL,(select tdc_codigo from sal.tdc_tipos_descuento where tdc_abreviatura = 'ISRGR' AND tdc_codcia = @codcia),NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'05b6bda7-ac4c-44f2-a9df-12e73406d28e',35,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'36a139d3-3575-4154-8865-3f00cf7689ac',36,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'9559bb84-5dfe-4a9d-aad8-f581d8cbe0f4',37,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'4b75e4c1-472f-4ad5-a3bf-3ed14d5b084b',38,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'953b2ed4-e94a-4fce-a966-f9dfb5816314',39,NULL,NULL,NULL,1);
insert into [sal].[fat_factores_tipo_planilla] ([fat_codtpl],[fat_codfac],[fat_precedencia],[fat_codtig],[fat_codtdc],[fat_codtrs],[fat_salva_en_tabla]) values ((select MAX(tpl_codigo) from sal.tpl_tipo_planilla where tpl_descripcion = 'Planilla Quincenal' and tpl_codmon = 'PAB'),'6e65914f-76c3-4adc-ba53-804823b17246',3,NULL,NULL,NULL,1);
COMMIT TRANSACTION
END TRY
BEGIN CATCH
	THROW;
END CATCH