select * into tbl_temp_pa_parametros from gen.par_parametros;
GO
delete from tbl_temp_pa_parametros;
GO
INSERT tbl_temp_pa_parametros (par_codigo, par_descripcion, par_tipo, par_unidad_medida, par_tipo_valor, par_property_bag_data, par_usuario_grabacion, par_fecha_grabacion, par_usuario_modificacion, par_fecha_modificacion) VALUES
('Anexo03_CodigoAgrupador_Bono', 'Código del agrupador para el Bono del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Anexo03_CodigoAgrupador_GastoRep', 'Código del agrupador para el Gasto de Representación del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Anexo03_CodigoAgrupador_Salario', 'Código del agrupador para el Salario del Anexo 03', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('BaseXIII_GastoRep_CodigoAgrupador', 'Código del agrupador para el base cálculo del décimo tercero del gasto de representación', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-08-04 08:28:44', NULL, NULL),
('BaseXIII_Salario_CodigoAgrupador', 'Código del agrupador para el base cálculo del décimo tercero del salario', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-08-04 08:26:49', NULL, NULL),
('CentroCostoEsRequerido', 'Indica si el centro de costo es requerido en las pantallas de hora extra, otros ingresos, ingresos ciclicos e ingresos eventuales', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoBancoBAC', 'Indica el código del catálogo de bancos que corresponde a BAC', 'Integer', 'Codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoDoc_Cedula', 'Código de tipo de documento que contiene el código de cédula', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoDoc_CedulaCSSExtranjeros', 'Código de tipo de documento que contiene el código de cédula según la CSS para Extranjeros', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-08-16 14:22:47', NULL, NULL),
('CodigoDoc_FichaDigitalCSS', 'Código de tipo de documento que contiene el código de ficha digital de la CSS', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-10-20 09:01:38', NULL, NULL),
('CodigoDoc_Pasaporte', 'Código del tipo de documento que tiene el pasaporte', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoDoc_SeguroSocial', 'Código de tipo de documento que contiene el código de afiliación al seguro social', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoFormaPagoCheque', 'Indica el código del catálogo de formas de pago que corresponde a Cheque', 'Integer', 'Codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoFormaPagoTransferencia', 'Indica el código del catálogo de formas de pago que corresponde a Transferencia Bancaria', 'Integer', 'Codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoRiesgoFondo', 'Código del riesgo de incapacidad que se utilizará para el fondo de incapacidad en Panamá', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('CodigoRiesgoMaternidad', 'Código del riesgo por Maternidad', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Codtig_DevolucionRenta', 'Tipo de ingreso devolución de renta', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('ContratacionValidaRubroSalario', 'determine si se hace la validación que verifica que exista al menos 1 rubro que esté asociado a Salario Base', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaEmpleadoSeguroEducativo', 'NULL', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaEmpleadoSeguroSocial', 'Cuota a descontar al empleado por seguro social', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaEmpleadoSeguroSocialXIII', 'NULL', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaPatronoRiesgoProfesional', 'Cuota a pagar por el patrono por riesgo profesional', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaPatronoSeguroEducativo', 'NULL', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaPatronoSeguroSocial', 'Cuota a pagar por el patrono por seguro social', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('CuotaPatronoSeguroSocialXIII', 'NULL', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('EndeudamientoMesesPromSalVar', 'Número de meses que se utilizan para calcular el promedio de Ingresos Variables para validar el endeudamiento de un empleado (define cuántos meses suma el parámetro [EndeudamientoCodAgrupadorVar])', 'Integer', 'Meses', 'E', NULL, NULL, NULL, NULL, NULL),
('EndeudamientoPorcentajeMax', 'Porcentaje máximo de endeudamiento de un empleado (sobre un agrupador que incluye los ingresos de la estructura salarial)', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('EndeudamientoValida', 'Determina si se verifica como regla de negocio el endeudamiento de un empleado al momento de salvar descuentos eventuales y cíclicos', 'Boolean', 'Verdadero/Falso', 'E', NULL, NULL, NULL, NULL, NULL),
('FondoCesantia_CodAgrupador_GastoRep', NULL, 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-06-28 08:40:54'),
('FondoCesantia_CodAgrupador_Salario', NULL, 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-06-28 08:41:17'),
('FondoIncapacidadDias', 'Días otorgados por año laborado PTY', 'Double', 'Dias', 'E', NULL, NULL, NULL, NULL, NULL),
('FondoIncapacidadMaximoDias', 'Máximo de días otorgados en fondo de incapacidad PTY', 'Double', 'Dias', 'E', NULL, NULL, NULL, NULL, NULL),
('HorasLaboradasPorMes', 'Parametro default para las horas laboradas por mes', 'Integer', 'Horas por mes', 'E', NULL, NULL, NULL, NULL, NULL),
('HorasLaboralesPorDia', 'Número de horas laborales por dia', 'Integer', 'Horas', 'E', NULL, NULL, NULL, NULL, NULL),
('IncapacidadesAntiguedadDiasParaProrrogar', 'Número de días a partir de la fecha fin de la incapacidad para poder prorrogar', 'Integer', 'Números positivos', 'E', NULL, NULL, NULL, NULL, NULL),
('ISRDeduccionLegal', 'Deducción legal según la clasificación de ISR del empleado', 'Double', 'Moneda', 'E', NULL, NULL, NULL, NULL, NULL),
('ISRNumeroMeses', 'Indica el número de meses para la anualización de renta', 'Integer', 'Meses', 'E', NULL, NULL, NULL, NULL, NULL),
('Liq_codtdc_renta', 'Tipo de Descuento Renta', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Liq_codtdc_rentaGastosRep', 'Tipo de Descuento Renta Gasto de Representación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Liq_codtig_aguinaldo', 'Tipo de ingreso Aguinaldo o Décimo Tercer Mes', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('MaximoSalarioContratacion', 'Indica si se verificará que el salario de la contratación no exceda el salario máximo de la clase salarial del puesto. Los alcances de este parámetro deben definirse solo para países o empresas.', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('MinimoSalarioContratacion', 'Indica si se verificará que el salario de la contratación no sea menor que el salario minimo de la clase salarial del puesto. Los alcances de este parámetro deben definirse solamente para países o empresas', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('MovimientoNumeroDiasParaAsociarAIncremento', 'Número de días a partir de la fecha de vigencia del movimiento para poder asociar a un incremento', 'Integer', 'Números positivos', 'E', NULL, NULL, NULL, NULL, NULL),
('PermiteVacacionPagada', 'Indica si se muestra el cheque para permitir que las solicitud de vacaciones sean pagadas', 'Boolean', 'Si / No', 'E', NULL, NULL, NULL, NULL, NULL),
('Preelaborada_CodigoAgrupador_Bono', 'Código del agrupador para el Bono del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Preelaborada_CodigoAgrupador_GastoRep', 'Código del agrupador para el Gasto de Representación del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Preelaborada_CodigoAgrupador_Gratificacion', 'Código del agrupador para Gratificaciones del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Preelaborada_CodigoAgrupador_Otros', 'Código del agrupador para Otros Salarios del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('Preelaborada_CodigoAgrupador_Salario', 'Código del agrupador para el Salario del reporte de Preelaborada', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Bono', 'Código de agrupador para el Informe Preelaborada SIPE columna Bonificación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Extras', 'Código de agrupador para el Informe Preelaborada SIPE columna Horas Extras', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_GastoRep', 'Código de agrupador para el Informe Preelaborada SIPE columna Gasto de Representación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Gratificacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Gratificación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, 'admin', '2016-07-21 12:58:55'),
('PreelaboradaSIPE_CodigoAgrupador_ISR', 'Código de agrupador para el Informe Preelaborada SIPE columna ISR', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_ISR_GR', 'Código de agrupador para el Informe Preelaborada SIPE columna ISR Gasto Representación', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-07-21 08:30:35', NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Liquidacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Prestaciones Liquidación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_OtrosIngresos', 'Código de agrupador para el Informe Preelaborada SIPE columna Otros Ingresos', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Participacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Participación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Preaviso', 'Código de agrupador para el Informe Preelaborada SIPE columna Preaviso', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Prima_Prod', 'Código de agrupador para el Informe Preelaborada SIPE columna Prima de Producción', 'Integer', 'codigo', 'E', NULL, 'admin', '2016-07-21 13:24:53', NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Salario', 'Código de agrupador para el Informe Preelaborada SIPE columna Salario', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Vacacion', 'Código de agrupador para el Informe Preelaborada SIPE columna Vacación', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_Viaticos', 'Código de agrupador para el Informe Preelaborada SIPE columna Viáticos', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('PreelaboradaSIPE_CodigoAgrupador_XIII', 'Código de agrupador para el Informe Preelaborada SIPE columna XIII mes', 'Integer', 'codigo', 'E', NULL, NULL, NULL, NULL, NULL),
('ProvisionIndemnizacion', 'Porcentaje de aplicación para Provisión de Indemnización', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('ProvisionPrimaAntiguedad', 'Porcentaje de aplicación para Provisión por Prima de Antiguedad', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('ProvisionVacacion', 'Porcentaje de aplicación para Provisión de Vacación', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('ProvisionXIIIMes', 'Porcentaje de aplicación para Provisión de XIII Mes', 'Double', 'Porcentaje', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojDiasDesplazamientoCortePlanilla', 'Número de días de desplazamiento para los cortes de marcas utilizado en el procedimiento de interpretación', 'Integer', 'Días', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojEstadoAsistenciaGenerada', 'Estado que se le asigna al registro de asistencia que se genera en el procedimiento de interpretación', 'String', 'N/A', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojEstadoWorkflowAsistenciaGenerada', 'Estado para flujo que se le asigna al registro de asistencia que se genera en el procedimiento de interpretación', 'String', 'N/A', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojMinutosEntreMarcasIguales', 'Número máximo de minutos entre dos marcas para ser consideradas como iguales', 'Integer', 'Minutos', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojTipoMarcaFallida', 'Estado que se asignará a la marca que no pudo procesarse por esta incorrecta', 'String', 'N/A', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojTipoMarcaNoProcesada', 'Estado que se asignará a la marca no procesada porque fue ignorada debido a la política implementada', 'String', 'N/A', 'E', NULL, NULL, NULL, NULL, NULL),
('RelojTipoMarcaProcesada', 'Estado que se asignará a la marca procesada', 'String', 'N/A', 'E', NULL, NULL, NULL, NULL, NULL),
('TablaRentaMensual', 'Tabla de Renta Mensual', 'Double', 'Dolares', 'R', NULL, NULL, NULL, NULL, NULL),
('TablaRentaMensualGastoRep', 'Tabla de renta mensual del gasto de representación', 'Double', 'Moneda', 'R', NULL, NULL, NULL, NULL, NULL),
('TiempoNoTrabajadoValidaTraslapeConPermiso', 'Indica si validarán el traslape de los tiempos no trabajados contra las solicitudes de permisos creados', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionDias', 'Dias de vacación que se deben adjudicar en un periodo', 'Integer', 'días', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionDiasAnterioridadPlanificacion', 'Número de días de anterioridad a partir de la fecha de aniversario de un empleo que se pueden planificar fechas de vacación en el Plan anual de vacaciones', 'Integer', 'Números positivos', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionHorasDia', 'Indica las horas asignadas para un día laboral', 'Integer', 'horas', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionIncluyeAsueto', 'Indica si los días de vacación incluyen asuetos', 'Boolean', 'si / no', 'R', NULL, NULL, NULL, NULL, NULL),
('VacacionIncluyeDomingo', 'Indica si la vacación incluye día domingo', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, 'admin', '2016-09-14 04:21:49'),
('VacacionIncluyeSabado', 'Indica si la vacación incluye sabados', 'Boolean', 'si / no', 'R', NULL, NULL, NULL, NULL, NULL),
('VacacionPermiteDiasConDecimal', 'Indica si en las vacaciones se permite el ingreso de dias con decimales. Nota: este parametro es excluyente con el parametro VacacionPermiteHoras', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionPermiteHoras', 'Indica si la vacación permite horas o no', 'Boolean', 'sí/no', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionPlanificadoPuedeFinalizarEnAsueto', 'Indica la fecha de finalización en el plan anual de vacaciones puede ser en día de asueto', 'Boolean', 'Si / No', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionPlanificadoPuedeIniciarEnAsueto', 'Indica la fecha de inicio en el plan anual de vacaciones puede ser en día de asueto', 'Boolean', 'Si / No', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionPlanificadoPuedeIniciarEnSeptimo', 'Indica la fecha de inicio en el plan anual de vacaciones puede ser en día de descanso', 'Boolean', 'Si / No', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionSabadoEsMediaJornada', 'Si se especifica que el calculo de días de vacación incluya el día sábado, con este parámetro se puede controlar que solo sume media jornada.  Este parámetro funciona solamente si se ha especificado que VacacionPermiteHoras = true o VacacionPermiteDiasConDecimal = true', 'Boolean', 'Si / No', 'E', NULL, NULL, NULL, 'admin', '2016-09-14 04:25:34'),
('VacacionUsaJornada', 'Indica si para calcular días hábiles se usa la jornada del empleado', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL),
('VacacionUsaSPParaCalculos', 'Indica si la vacación debe usar Stored Procedure para calcular la duración y la fecha final', 'Boolean', 'si / no', 'E', NULL, NULL, NULL, NULL, NULL);
GO
insert gen.par_parametros select * from tbl_temp_pa_parametros where par_codigo not in (select par_codigo from gen.par_parametros);
GO
drop table tbl_temp_pa_parametros;
GO
select * into tbl_temp_apa_alcances_parametros from gen.apa_alcances_parametros;
GO
delete from tbl_temp_apa_alcances_parametros;
GO
INSERT tbl_temp_apa_alcances_parametros(apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) VALUES (NULL, NULL, 'HorasLaboradasPorMes', 'pa', NULL, NULL, NULL, '208', NULL, NULL, NULL, NULL),
( NULL, NULL, 'HorasLaboralesPorDia', 'pa', NULL, NULL, NULL, '8', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionDias', 'pa', NULL, NULL, NULL, '30', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionIncluyeSabado', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionIncluyeDomingo', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionIncluyeAsueto', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionUsaJornada', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionSabadoEsMediaJornada', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'EndeudamientoValida', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'EndeudamientoPorcentajeMax', 'pa', NULL, NULL, NULL, '30', NULL, NULL, NULL, NULL),
( NULL, NULL, 'EndeudamientoMesesPromSalVar', 'pa', NULL, NULL, NULL, '6', NULL, NULL, NULL, NULL),
( NULL, NULL, 'ContratacionValidaRubroSalario', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionPermiteDiasConDecimal', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CentroCostoEsRequerido', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'PermiteVacacionPagada', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionUsaSPParaCalculos', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'IncapacidadesAntiguedadDiasParaProrrogar', 'pa', NULL, NULL, NULL, '30', NULL, NULL, NULL, NULL),
( NULL, NULL, 'MovimientoNumeroDiasParaAsociarAIncremento', 'pa', NULL, NULL, NULL, '30', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionDiasAnterioridadPlanificacion', 'pa', NULL, NULL, NULL, '30', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionPlanificadoPuedeIniciarEnSeptimo', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionPlanificadoPuedeIniciarEnAsueto', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionPlanificadoPuedeFinalizarEnAsueto', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoDoc_Cedula', 'pa', NULL, NULL, NULL, '10', 'admin', '2016-02-01 16:04:22', NULL, NULL),
( NULL, NULL, 'CodigoDoc_SeguroSocial', 'pa', NULL, NULL, NULL, '11', 'admin', '2016-02-01 16:05:05', NULL, NULL),
( NULL, NULL, 'CodigoDoc_Pasaporte', 'pa', NULL, NULL, NULL, '12', 'admin', '2016-02-01 16:06:56', NULL, NULL),
( NULL, NULL, 'RelojDiasDesplazamientoCortePlanilla', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojEstadoAsistenciaGenerada', 'pa', NULL, NULL, NULL, 'Pendiente', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojEstadoWorkflowAsistenciaGenerada', 'pa', NULL, NULL, NULL, 'Pendiente', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojMinutosEntreMarcasIguales', 'pa', NULL, NULL, NULL, '10', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojTipoMarcaFallida', 'pa', NULL, NULL, NULL, 'Fallida', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojTipoMarcaNoProcesada', 'pa', NULL, NULL, NULL, 'No Procesada', NULL, NULL, NULL, NULL),
( NULL, NULL, 'RelojTipoMarcaProcesada', 'pa', NULL, NULL, NULL, 'Procesada', NULL, NULL, NULL, NULL),
( NULL, NULL, 'MaximoSalarioContratacion', 'pa', NULL, NULL, NULL, '0', 'genezarett.valdes', '2016-03-04 15:53:36', NULL, NULL),
( NULL, NULL, 'MinimoSalarioContratacion', 'pa', NULL, NULL, NULL, '0', 'genezarett.valdes', '2016-03-04 15:54:03', NULL, NULL),
( NULL, NULL, 'CodigoRiesgoFondo', 'pa', NULL, NULL, NULL, '1', NULL, NULL, 'admin', '2016-04-01 10:36:30'),
( NULL, NULL, 'ISRDeduccionLegal', 'pa', NULL, NULL, NULL, '800', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaPatronoSeguroSocial', 'pa', NULL, NULL, NULL, '12.25', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaPatronoSeguroSocialXIII', 'pa', NULL, NULL, NULL, '10.75', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaPatronoSeguroEducativo', 'pa', NULL, NULL, NULL, '1.5', NULL, NULL, NULL, NULL),
( NULL, NULL, 'ProvisionIndemnizacion', 'pa', NULL, NULL, NULL, '0.33', NULL, NULL, NULL, NULL),
( NULL, NULL, 'ProvisionPrimaAntiguedad', 'pa', NULL, NULL, NULL, '1.923', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaPatronoRiesgoProfesional', 'pa', NULL, NULL, NULL, '2.52', NULL, NULL, 'admin', '2016-09-30 10:01:38'),
( NULL, NULL, 'ProvisionVacacion', 'pa', NULL, NULL, NULL, '9.09', NULL, NULL, 'admin', '2016-10-10 10:52:47'),
( NULL, NULL, 'ProvisionXIIIMes', 'pa', NULL, NULL, NULL, '8.333', NULL, NULL, 'admin', '2016-10-10 12:44:57'),
( NULL, NULL, 'Liq_codtdc_renta', 'pa', NULL, NULL, NULL, '3', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Liq_codtdc_rentaGastosRep', 'pa', NULL, NULL, NULL, '4', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Liq_codtig_aguinaldo', 'pa', NULL, NULL, NULL, '3', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Codtig_DevolucionRenta', 'pa', NULL, NULL, NULL, '34', NULL, NULL, NULL, NULL),
( NULL, NULL, 'FondoIncapacidadDias', 'pa', NULL, NULL, NULL, '18', NULL, NULL, NULL, NULL),
( NULL, NULL, 'FondoIncapacidadMaximoDias', 'pa', NULL, NULL, NULL, '36', NULL, NULL, NULL, NULL),
( NULL, NULL, 'ISRNumeroMeses', 'pa', NULL, NULL, NULL, '13', NULL, NULL, NULL, NULL),
( NULL, NULL, 'TablaRentaMensual', 'pa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaEmpleadoSeguroSocial', 'pa', NULL, NULL, NULL, '9.75', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaEmpleadoSeguroEducativo', 'pa', NULL, NULL, NULL, '1.25', NULL, NULL, NULL, NULL),
( NULL, NULL, 'TablaRentaMensualGastoRep', 'pa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionHorasDia', 'pa', NULL, NULL, NULL, '8', NULL, NULL, NULL, NULL),
( NULL, NULL, 'VacacionPermiteHoras', 'pa', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoRiesgoMaternidad', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaEmpleadoSeguroSocialXIII', 'pa', NULL, NULL, NULL, '7.25', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoBancoBAC', 'pa', NULL, NULL, NULL, '2', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoFormaPagoTransferencia', 'pa', NULL, NULL, NULL, '3', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoFormaPagoCheque', 'pa', NULL, NULL, NULL, '2', NULL, NULL, NULL, NULL),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '60', NULL, NULL, 'admin', '2016-07-21 08:25:26'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Extras', 'pa', NULL, NULL, NULL, '57', NULL, NULL, 'admin', '2016-07-21 08:25:53'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '59', NULL, NULL, 'admin', '2016-07-21 08:26:15'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_ISR', 'pa', NULL, NULL, NULL, '62', NULL, NULL, 'admin', '2016-07-21 08:26:33'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Liquidacion', 'pa', NULL, NULL, NULL, '65', NULL, NULL, 'admin', '2016-07-21 08:26:58'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_OtrosIngresos', 'pa', NULL, NULL, NULL, '67', NULL, NULL, 'admin', '2016-07-21 08:27:20'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Participacion', 'pa', NULL, NULL, NULL, '63', NULL, NULL, 'admin', '2016-07-21 08:27:36'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Preaviso', 'pa', NULL, NULL, NULL, '66', NULL, NULL, 'admin', '2016-07-21 08:27:56'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '56', NULL, NULL, 'admin', '2016-07-21 08:28:11'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Vacacion', 'pa', NULL, NULL, NULL, '58', NULL, NULL, 'admin', '2016-07-21 08:28:26'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Viaticos', 'pa', NULL, NULL, NULL, '64', NULL, NULL, 'admin', '2016-07-21 08:28:48'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_XIII', 'pa', NULL, NULL, NULL, '61', NULL, NULL, 'admin', '2016-07-21 08:29:05'),
( NULL, NULL, 'Anexo03_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '1055', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Anexo03_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '75', NULL, NULL, 'admin', '2016-09-13 08:13:10'),
( NULL, NULL, 'Anexo03_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '77', NULL, NULL, 'admin', '2016-09-13 08:11:14'),
( NULL, NULL, 'Preelaborada_CodigoAgrupador_Bono', 'pa', NULL, NULL, NULL, '1052', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Preelaborada_CodigoAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '1050', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Preelaborada_CodigoAgrupador_Gratificacion', 'pa', NULL, NULL, NULL, '1053', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Preelaborada_CodigoAgrupador_Otros', 'pa', NULL, NULL, NULL, '1051', NULL, NULL, NULL, NULL),
( NULL, NULL, 'Preelaborada_CodigoAgrupador_Salario', 'pa', NULL, NULL, NULL, '1049', NULL, NULL, NULL, NULL),
( NULL, NULL, 'FondoCesantia_CodAgrupador_Salario', 'pa', NULL, NULL, NULL, '68', NULL, NULL, 'admin', '2016-06-28 08:40:38'),
( NULL, NULL, 'FondoCesantia_CodAgrupador_GastoRep', 'pa', NULL, NULL, NULL, '69', NULL, NULL, 'admin', '2016-06-28 08:41:04'),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_ISR_GR', 'pa', NULL, NULL, NULL, '81', 'admin', '2016-07-21 08:30:51', NULL, NULL),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Gratificacion', 'pa', NULL, NULL, NULL, '83', 'admin', '2016-07-21 12:58:52', NULL, NULL),
( NULL, NULL, 'PreelaboradaSIPE_CodigoAgrupador_Prima_Prod', 'pa', NULL, NULL, NULL, '84', 'admin', '2016-07-21 13:25:13', NULL, NULL),
( NULL, NULL, 'BaseXIII_Salario_CodigoAgrupador', 'pa', NULL, NULL, NULL, '33', 'admin', '2016-08-04 08:27:52', NULL, NULL),
( NULL, NULL, 'BaseXIII_GastoRep_CodigoAgrupador', 'pa', NULL, NULL, NULL, '46', 'admin', '2016-08-04 08:28:59', NULL, NULL),
( NULL, NULL, 'CodigoDoc_CedulaCSSExtranjeros', 'pa', NULL, NULL, NULL, '15', 'admin', '2016-08-16 14:22:59', NULL, NULL),
( NULL, NULL, 'TiempoNoTrabajadoValidaTraslapeConPermiso', 'pa', NULL, NULL, NULL, '0', 'admin', '2016-09-30 08:54:17', NULL, NULL),
( NULL, NULL, 'CodigoDoc_FichaDigitalCSS', 'pa', NULL, NULL, NULL, '16', 'admin', '2016-10-20 09:01:57', NULL, NULL),
( NULL, NULL, 'CodigoRubroSalario', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CodigoPlanillaQuincenal', 'pa', NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaEmpleadoSeguroSocial', 'pa', NULL, NULL, NULL, '9.75', NULL, NULL, NULL, NULL),
( NULL, NULL, 'CuotaPatronoSeguroSocial', 'pa', NULL, NULL, NULL, '12.25', NULL, NULL, NULL, NULL)
GO
insert into gen.apa_alcances_parametros(apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion) select apa_fecha_inicio, apa_fecha_final, apa_codpar, apa_codpai, apa_codgrc, apa_codcia, apa_codcdt, apa_valor, apa_usuario_grabacion, apa_fecha_grabacion, apa_usuario_modificacion, apa_fecha_modificacion from tbl_temp_apa_alcances_parametros
where apa_codpar not in (select apa_codpar from gen.apa_alcances_parametros) and apa_codpai = 'pa' and apa_codpar in (select par_codigo from gen.par_parametros);
GO
drop table tbl_temp_apa_alcances_parametros;
